name: Release
concurrency: deploy-to-prod-workflow
on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  test-storybook:
    uses: "./.github/workflows/storybook.yml"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Playwright tests job
  test-playwright:
    uses: "./.github/workflows/playwright.yml"

  chromatic:
    uses: "./.github/workflows/chromatic.yml"
    # secrets:
    #   CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  build-and-deploy-to-prod:
    # This permissions block wasn't needed in
    # earlier versions of semantic-release
    # (I have a project currently using an
    # earlier version and it works fine without
    # a permissions block anywhere in the workflow)
    # The issue is described here:
    # https://github.com/semantic-release/semantic-release/issues/2481
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    needs: [test-storybook, test-playwright, chromatic]
    name: Deploy to Production
    steps:
      - uses: actions/checkout@v3
        name: Checkout code
        id: checkout
        with:
          submodules: true
      - name: Install Vercel CLI

        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information

        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Create GitHub release
        id: semanticrelease
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm ci
          npm run release

      # NEXT, THERE SHOULD ACTUAL DEPLOYMENT STEPS
      # (to deploy to NPM, or Vercel or AWS Amplify
      # or Google Firebase or Azure Static Web Apps etc.)
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
