name: CI
concurrency: ci-${{ github.ref }}
permissions:
  checks: write
  pull-requests: write
on:
  pull_request:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  test-storybook:
    uses: "./.github/workflows/storybook.yml"

  # Playwright tests job
  test-playwright:
    uses: "./.github/workflows/playwright.yml"
    with:
      show-pr-comment: true

  build-and-deploy-to-preview:
    name: Build and Deploy to preview env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
