name: CI
concurrency: ci-${{ github.ref }}
permissions:
  checks: write
  pull-requests: write
on:
  pull_request:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  test-storybook:
    runs-on: ubuntu-22.04
    name: Storybook tests
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.5.3

      - name: Build storybook
        run: |
          npm install
          npm run build-storybook

      - name: Run test-runner for component smoke and interaction tests with coverage
        env:
          JEST_JUNIT_OUTPUT_FILE: testrunreports/storybooktests-junit.xml

        run: |
          npm run test-storybook:ci

          - name: Publish storybook test report
          uses: dorny/test-reporter@v1
          # run this step even if previous step failed:
          if: success() || failure()
          with:
            name: Story test report # Name of the check run which will be created
            path: testrunreports/*-junit.xml # Path to test results
            reporter: jest-junit # Format of test results

      - name: Upload raw coverage as artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test-runner coverage file
          path: coverage/storybook/coverage-storybook.json

      - name: Run accessibility tests
        # these do not generate coverage
        run: |
          npm run test-storybook-a11y:ci

      - name:
          Massage a11y test run report
          # Need to add a testssuites element that wraps the
          # only (and outermost) testsuite element in the
          # test run report output by aze-storybook-testing
          # a11y tester for storybook that we're using.
        run: |
          t=$(grep -oP  -m 1 "(?<=time=\")(.*)(?=\")" testrunreports/a11ytests.xml)
          echo "<testsuites time=\"${t}\">" >> testrunreports/a11ytests-fixed.xml
          cat testrunreports/a11ytests.xml >> testrunreports/a11ytests-fixed.xml
          echo '</testsuites>' >> testrunreports/a11ytests-fixed.xml

      - name: Publish Storybook a11y test report
        uses: dorny/test-reporter@v1
        # run this step even if previous step failed:
        if: success() || failure()
        with:
          name: Storybook a11y test report # Name of the check run which will be created
          path: testrunreports/a11ytests-fixed.xml # Path to test results
          reporter: jest-junit # Format of test results

  build-and-deploy-to-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
