name: commit-lint

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]

jobs:
  lint-commit-message:
    name: Lint commit message
    runs-on: ubuntu-latest

    steps:
      - uses: ahmadnassri/action-commit-lint@v1
